services:
  - type: web
    name: cv-generator-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: false
    healthCheckPath: /health
    autoDeploy: true
